# Generated by Django 4.2.16 on 2024-09-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_alter_message_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
