# Generated by Django 4.2.16 on 2024-09-19 18:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
        migrations.RemoveField(
            model_name='work',
            name='title',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_image',
        ),
        migrations.AddField(
            model_name='work',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='live_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='project_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='work',
            name='project_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
