# Generated by Django 4.2.16 on 2024-09-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
