# Generated by Django 4.2.16 on 2024-09-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='views',
        ),
    ]
