# Generated by Django 4.2.16 on 2024-09-21 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0013_remove_work_views'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='view',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='view',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
