# Generated by Django 4.2.16 on 2024-09-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='project',
            new_name='work',
        ),
    ]
